export const rawProducts = [
  {
    slug: "bugis-folding-chair",
    name: "Bugis Folding Chair",
    sku: "ONE59-DIN-001",
    categorySlug: "dining",
    catalogType: "drop",
    dropSlug: "payday-reset",
    price: 39,
    image: "/images/folding-chair.webp",
    tone: "ember",
    badge: "Drop pick",
    stockStatus: "in_stock",
    summary: "A slim steel folding chair that disappears fast when guests leave.",
    highlights: [
      "Pre-assembled and ready to use out of the box",
      "Easy fold profile for tighter dining corners",
      "Textured seat that wipes down quickly after everyday meals",
    ],
    dimensions: "W45 × D46 × H78 cm",
    materials: "Powder-coated steel frame, textured PP seat",
    finish: "Matte sand seat with black frame",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    specs: [
      { label: "Best for", value: "Dining corners, hot-desk guests, rental kitchens" },
      { label: "Care", value: "Wipe clean with a soft damp cloth" },
      { label: "Weight", value: "3.6 kg" },
    ],
    socialProof: {
      rating: 4.8,
      reviews: 64,
      quote: "Bought two for weekday dinners and they still look good enough for weekend guests.",
      person: "Nadia, Queenstown",
    },
    alternativeSlugs: ["marina-tray-table"],
  },
  {
    slug: "marina-tray-table",
    name: "Marina Tray Table",
    sku: "ONE59-DIN-002",
    categorySlug: "dining",
    catalogType: "evergreen",
    price: 79,
    image: "/images/tray-table.webp",
    tone: "sand",
    badge: "Evergreen",
    stockStatus: "in_stock",
    summary: "A fold-flat tray table for late breakfasts, laptop lunches, and flexible hosting.",
    highlights: [
      "Tucks away when the floor plan needs to change",
      "Rounded edges keep the look softer in tighter rooms",
      "Factory-direct pricing keeps it well under the S$159 promise",
    ],
    dimensions: "W58 × D38 × H66 cm",
    materials: "Bamboo top, powder-coated steel base",
    finish: "Warm natural bamboo",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    specs: [
      { label: "Best for", value: "Breakfast setups, laptops, side serving" },
      { label: "Care", value: "Dry cloth or mild soap only" },
      { label: "Weight", value: "4.8 kg" },
    ],
    socialProof: {
      rating: 4.9,
      reviews: 87,
      quote: "Looks far more expensive than S$79 and arrived exactly when promised.",
      person: "Marcus, Bukit Panjang",
    },
    alternativeSlugs: ["bugis-folding-chair"],
  },
  {
    slug: "tanjong-floor-cushion",
    name: "Tanjong Floor Cushion",
    sku: "ONE59-LIV-001",
    categorySlug: "living",
    catalogType: "drop",
    dropSlug: "payday-reset",
    price: 49,
    image: "/images/floor-cushion.webp",
    tone: "clay",
    badge: "Live drop",
    stockStatus: "low_stock",
    summary: "An oversized floor cushion for movie nights, reading corners, and low-lift hosting.",
    highlights: [
      "Soft enough for lounging, structured enough to hold shape",
      "Works in living rooms, study corners, and nursery spillover zones",
      "Comes pre-filled so there is no setup drama on arrival",
    ],
    dimensions: "W68 × D68 × H18 cm",
    materials: "Cotton blend cover, polyfill insert",
    finish: "Clay beige",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    specs: [
      { label: "Best for", value: "Movie nights, reading corners, extra guests" },
      { label: "Care", value: "Spot clean outer cover only" },
      { label: "Weight", value: "2.4 kg" },
    ],
    socialProof: {
      rating: 4.7,
      reviews: 38,
      quote: "We bought one as a trial and went back for a second by the weekend.",
      person: "Elaine, Tampines",
    },
    alternativeSlugs: ["toa-plastic-stool"],
  },
  {
    slug: "toa-plastic-stool",
    name: "Toa Utility Stool",
    sku: "ONE59-LIV-002",
    categorySlug: "living",
    catalogType: "evergreen",
    price: 29,
    image: "/images/plastic-stool.webp",
    tone: "sage",
    badge: "Fast mover",
    stockStatus: "sold_out",
    summary: "A stack-friendly stool that works as a seat, side perch, or plant stand in a pinch.",
    highlights: [
      "Useful in balconies, bathrooms, and hosting overflow",
      "Lightweight build makes room resets easy",
      "Popular as a quick win for smaller flats",
    ],
    dimensions: "W31 × D31 × H45 cm",
    materials: "High-density molded plastic",
    finish: "Soft olive matte",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore when restocked",
    specs: [
      { label: "Best for", value: "Balconies, side seating, plant styling" },
      { label: "Care", value: "Wipe clean and avoid harsh abrasives" },
      { label: "Weight", value: "1.9 kg" },
    ],
    socialProof: {
      rating: 4.8,
      reviews: 112,
      quote: "Sold out before I could buy a second one, which says everything.",
      person: "Aqilah, Jurong East",
    },
    alternativeSlugs: ["tanjong-floor-cushion"],
  },
  {
    slug: "joo-chiat-bedside-table",
    name: "Joo Chiat Bedside Table",
    sku: "ONE59-BED-001",
    categorySlug: "bedroom",
    catalogType: "evergreen",
    price: 129,
    image: "/images/bedside-table.webp",
    tone: "sand",
    badge: "Best seller",
    stockStatus: "low_stock",
    summary: "A clean-lined bedside table with one drawer and just enough storage for the nightly essentials.",
    highlights: [
      "Drawer hides the visual clutter quickly",
      "Compact footprint suits HDB and condo bedrooms alike",
      "Arrives fully built so setup takes minutes, not hours",
    ],
    dimensions: "W42 × D35 × H50 cm",
    materials: "Engineered wood, melamine finish, powder-coated handle",
    finish: "Warm oat woodgrain",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    specs: [
      { label: "Best for", value: "Bedside storage, guest rooms, rental upgrades" },
      { label: "Care", value: "Dry cloth and no standing water" },
      { label: "Weight", value: "11.2 kg" },
    ],
    socialProof: {
      rating: 4.9,
      reviews: 71,
      quote: "The finish feels calm and expensive without pushing over budget.",
      person: "Jia Xin, Hougang",
    },
    alternativeSlugs: ["sengkang-wall-mirror"],
  },
  {
    slug: "sengkang-wall-mirror",
    name: "Sengkang Wall Mirror",
    sku: "ONE59-BED-002",
    categorySlug: "bedroom",
    catalogType: "evergreen",
    price: 59,
    image: "/images/wall-mirror.webp",
    tone: "slate",
    badge: "Always on",
    stockStatus: "in_stock",
    summary: "A minimal wall mirror that brightens smaller rooms and entry-side corners instantly.",
    highlights: [
      "Soft rounded frame keeps the look lighter than a square mirror",
      "Works equally well in bedrooms, dressing corners, and entry walls",
      "A high-impact refresh for under S$59 with GST already included",
    ],
    dimensions: "W46 × D3 × H66 cm",
    materials: "Aluminium frame, mirrored glass",
    finish: "Graphite frame",
    assembly: "Wall mount required",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    specs: [
      { label: "Best for", value: "Visual light, outfit checks, entry styling" },
      { label: "Care", value: "Glass cleaner on cloth, not directly on mirror" },
      { label: "Weight", value: "4.4 kg" },
    ],
    socialProof: {
      rating: 4.8,
      reviews: 58,
      quote: "The proportions are just right for compact bedrooms in Singapore apartments.",
      person: "Darren, Serangoon",
    },
    alternativeSlugs: ["joo-chiat-bedside-table"],
  },
  {
    slug: "queenstown-desk-lamp",
    name: "Queenstown Desk Lamp",
    sku: "ONE59-WRK-001",
    categorySlug: "workspace",
    catalogType: "drop",
    dropSlug: "study-corner",
    price: 45,
    image: "/images/desk-lamp.webp",
    tone: "ember",
    badge: "Night shift",
    stockStatus: "in_stock",
    summary: "A compact desk lamp with a clean silhouette and warm task lighting for WFH corners.",
    highlights: [
      "Helps smaller desks feel styled, not temporary",
      "Warm light tone flatters study corners during late hours",
      "Pairs naturally with slim desks and storage bins",
    ],
    dimensions: "W18 × D18 × H39 cm",
    materials: "Powder-coated steel, ABS diffuser",
    finish: "Burnt sienna",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    specs: [
      { label: "Best for", value: "Study corners, bedroom desks, night reading" },
      { label: "Care", value: "Soft dry cloth only" },
      { label: "Weight", value: "1.4 kg" },
    ],
    socialProof: {
      rating: 4.7,
      reviews: 42,
      quote: "Exactly the kind of desk lamp you see in moodboards, minus the scary price.",
      person: "Faris, Clementi",
    },
    alternativeSlugs: ["paya-laptop-desk"],
  },
  {
    slug: "paya-laptop-desk",
    name: "Paya Laptop Desk",
    sku: "ONE59-WRK-002",
    categorySlug: "workspace",
    catalogType: "evergreen",
    price: 99,
    image: "/images/laptop-desk.webp",
    tone: "slate",
    badge: "WFH staple",
    stockStatus: "in_stock",
    summary: "A narrow-profile laptop desk for getting a proper setup into rooms that do not really have room.",
    highlights: [
      "Slim depth keeps circulation clear in shared rooms",
      "Built for laptops, notebooks, and compact monitors",
      "A good match for the current study-corner drop window",
    ],
    dimensions: "W80 × D40 × H75 cm",
    materials: "Powder-coated steel, laminate top",
    finish: "Charcoal frame with ash top",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    specs: [
      { label: "Best for", value: "WFH setups, tuition desks, compact bedrooms" },
      { label: "Care", value: "Soft cloth and mild cleaner" },
      { label: "Weight", value: "8.3 kg" },
    ],
    socialProof: {
      rating: 4.9,
      reviews: 93,
      quote: "The exact reason I tried One59 — it looks designed, not makeshift.",
      person: "Melissa, Bedok",
    },
    alternativeSlugs: ["queenstown-desk-lamp"],
  },
  {
    slug: "hougang-cube-bin",
    name: "Hougang Cube Bin",
    sku: "ONE59-STO-001",
    categorySlug: "storage",
    catalogType: "evergreen",
    price: 19,
    image: "/images/cube-bin.webp",
    tone: "sage",
    badge: "Fast restock",
    stockStatus: "in_stock",
    summary: "A soft-sided storage cube that makes open shelving look deliberate instead of messy.",
    highlights: [
      "Folds flat when not in use",
      "Tidy enough for open shelves in living rooms and bedrooms",
      "One of the lowest-friction under-S$159 entry points to the brand",
    ],
    dimensions: "W29 × D29 × H29 cm",
    materials: "Fabric shell, reinforced insert base",
    finish: "Warm stone",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    specs: [
      { label: "Best for", value: "Open shelves, toys, cables, wardrobe extras" },
      { label: "Care", value: "Spot clean and air dry" },
      { label: "Weight", value: "0.7 kg" },
    ],
    socialProof: {
      rating: 4.8,
      reviews: 121,
      quote: "The quickest way to make a shelf look finished before people come over.",
      person: "Hui Min, Pasir Ris",
    },
    alternativeSlugs: ["yishun-wall-shelf", "bedok-shoe-rack"],
  },
  {
    slug: "yishun-wall-shelf",
    name: "Yishun Wall Shelf",
    sku: "ONE59-STO-002",
    categorySlug: "storage",
    catalogType: "drop",
    dropSlug: "payday-reset",
    price: 55,
    image: "/images/wall-shelf.webp",
    tone: "sage",
    badge: "Drop exclusive",
    stockStatus: "sold_out",
    summary: "A shallow wall shelf for decor, daily grab items, and visual storage above the floor line.",
    highlights: [
      "Perfect for vertical storage when floor space is tight",
      "Styled enough for bedrooms, entryways, and WFH corners",
      "The first item to sell through in the current payday drop",
    ],
    dimensions: "W60 × D18 × H20 cm",
    materials: "Pine veneer shelf, concealed bracket",
    finish: "Mid-oak",
    assembly: "Wall mount required",
    delivery: "Ships in 3 to 5 days across mainland Singapore on next allocation",
    specs: [
      { label: "Best for", value: "Vertical storage, display, entry essentials" },
      { label: "Care", value: "Dust with a dry microfiber cloth" },
      { label: "Weight", value: "3.8 kg" },
    ],
    socialProof: {
      rating: 4.8,
      reviews: 55,
      quote: "Exactly the kind of product that sells out because every room can use one.",
      person: "Rina, Sembawang",
    },
    alternativeSlugs: ["hougang-cube-bin", "bedok-shoe-rack", "ang-mo-kio-coat-rack"],
  },
  {
    slug: "bedok-shoe-rack",
    name: "Bedok Shoe Rack",
    sku: "ONE59-STO-003",
    categorySlug: "storage",
    catalogType: "evergreen",
    price: 89,
    image: "/images/shoe-rack.webp",
    tone: "sand",
    badge: "Entryway fix",
    stockStatus: "in_stock",
    summary: "A compact shoe rack with enough polish to stay visible instead of being hidden away.",
    highlights: [
      "Keeps everyday pairs organised without looking utilitarian",
      "Works especially well with mirrors and coat stands in smaller foyers",
      "Designed to make the first 2 metres of your home feel calmer",
    ],
    dimensions: "W72 × D28 × H54 cm",
    materials: "Powder-coated steel, wood-look shelves",
    finish: "Sand oak shelves with charcoal frame",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    specs: [
      { label: "Best for", value: "Entryways, rental foyers, spare-room doors" },
      { label: "Care", value: "Dry cloth or mild soap" },
      { label: "Weight", value: "6.1 kg" },
    ],
    socialProof: {
      rating: 4.9,
      reviews: 79,
      quote: "Made our entrance look intentional instead of like a shoe pile.",
      person: "Shafiq, Woodlands",
    },
    alternativeSlugs: ["ang-mo-kio-coat-rack", "hougang-cube-bin"],
  },
  {
    slug: "ang-mo-kio-coat-rack",
    name: "Ang Mo Kio Coat Rack",
    sku: "ONE59-STO-004",
    categorySlug: "storage",
    catalogType: "drop",
    dropSlug: "entryway-flip",
    price: 119,
    image: "/images/coat-rack.webp",
    tone: "clay",
    badge: "Upcoming drop",
    stockStatus: "in_stock",
    summary: "A vertical coat rack that makes the entryway feel sorted before anyone reaches the living room.",
    highlights: [
      "Tall profile, small footprint",
      "Eight hooks handle bags, umbrellas, and quick-grab layers",
      "Set up for the next drop window with the entryway collection",
    ],
    dimensions: "W38 × D38 × H170 cm",
    materials: "Solid rubberwood, matte protective coat",
    finish: "Smoked walnut",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore once the drop opens",
    specs: [
      { label: "Best for", value: "Entryways, bedrooms, guest-ready resets" },
      { label: "Care", value: "Dry cloth and occasional wood-safe polish" },
      { label: "Weight", value: "7.5 kg" },
    ],
    socialProof: {
      rating: 4.7,
      reviews: 24,
      quote: "The upcoming drop piece everyone in our group chat saved first.",
      person: "Wei Lin, Bishan",
    },
    alternativeSlugs: ["bedok-shoe-rack", "hougang-cube-bin"],
  },
  {
    slug: "commonwealth-nesting-side-table",
    name: "Commonwealth Nesting Side Table",
    sku: "ONE59-LIV-003",
    categorySlug: "living",
    catalogType: "drop",
    dropSlug: "payday-reset",
    price: 69,
    tone: "clay",
    badge: "Fresh in drop",
    stockStatus: "in_stock",
    summary: "A pair of light nesting tables that pull out for hosting and tuck back in when the room needs breathing space.",
    highlights: [
      "Two-piece set lets smaller living rooms flex between daily use and guests",
      "Rounded tops keep the silhouette softer around sofas and floor cushions",
      "Compact enough for HDB corners that cannot spare a full coffee table",
    ],
    dimensions: "Large: W48 × D38 × H46 cm · Small: W40 × D32 × H40 cm",
    materials: "Powder-coated steel base, wood-look MDF top",
    finish: "Clay oak top with warm rust frame",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    shape: "sidetable",
    color: "#b76e55",
    specs: [
      { label: "Best for", value: "Living corners, guest snacks, flexible coffee-table duty" },
      { label: "Care", value: "Dry cloth and no standing moisture" },
      { label: "Weight", value: "6.4 kg combined" },
    ],
    socialProof: {
      rating: 4.8,
      reviews: 36,
      quote: "The nesting trick makes our small sofa corner feel far more expensive and usable.",
      person: "Rachel, Bukit Merah",
    },
    alternativeSlugs: ["tanjong-floor-cushion", "marina-tray-table"],
  },
  {
    slug: "bukit-timah-accent-lounge-chair",
    name: "Bukit Timah Accent Lounge Chair",
    sku: "ONE59-LIV-004",
    categorySlug: "living",
    catalogType: "evergreen",
    price: 149,
    tone: "sand",
    badge: "Living-room upgrade",
    stockStatus: "low_stock",
    summary: "A cushioned lounge chair with a compact footprint and enough polish to anchor a reading corner properly.",
    highlights: [
      "Compact arms make it easier to fit into bedroom corners and smaller living rooms",
      "Textured upholstery feels calmer than shiny synthetic seating",
      "Sits low enough to pair naturally with floor cushions and side tables",
    ],
    dimensions: "W66 × D70 × H76 cm",
    materials: "Powder-coated steel frame, foam seat, woven polyester upholstery",
    finish: "Warm oatmeal upholstery with matte black frame",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    shape: "chair",
    color: "#a98b74",
    specs: [
      { label: "Best for", value: "Reading corners, rental living rooms, bedroom spillover seating" },
      { label: "Care", value: "Vacuum gently and spot clean with upholstery-safe solution" },
      { label: "Weight", value: "9.1 kg" },
    ],
    socialProof: {
      rating: 4.9,
      reviews: 29,
      quote: "It looks far more expensive than it is, but still fits the room budget comfortably.",
      person: "Zhi Wei, Novena",
    },
    alternativeSlugs: ["tanjong-floor-cushion", "commonwealth-nesting-side-table"],
  },
  {
    slug: "toa-payoh-bedside-caddy",
    name: "Toa Payoh Bedside Caddy",
    sku: "ONE59-BED-003",
    categorySlug: "bedroom",
    catalogType: "evergreen",
    price: 49,
    tone: "sage",
    badge: "Quiet essential",
    stockStatus: "in_stock",
    summary: "A slim bedside caddy with an open shelf and lip tray for the nightly things you always reach for first.",
    highlights: [
      "Open top keeps chargers, glasses, and water within easy reach",
      "Narrow width suits tighter bedrooms where a full nightstand feels bulky",
      "Fastest way to make a guest room feel intentionally furnished",
    ],
    dimensions: "W28 × D24 × H58 cm",
    materials: "Powder-coated steel frame, veneer-look tray shelf",
    finish: "Muted sage frame with oat shelf",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    shape: "sidetable",
    color: "#6d7d67",
    specs: [
      { label: "Best for", value: "Small bedrooms, guest rooms, compact bedside storage" },
      { label: "Care", value: "Dry cloth and gentle cleaner on tray surface" },
      { label: "Weight", value: "3.7 kg" },
    ],
    socialProof: {
      rating: 4.8,
      reviews: 51,
      quote: "Exactly enough bedside storage without making the room feel crowded.",
      person: "Amanda, Toa Payoh",
    },
    alternativeSlugs: ["joo-chiat-bedside-table", "sengkang-wall-mirror"],
  },
  {
    slug: "serangoon-bed-end-bench",
    name: "Serangoon Bed-End Bench",
    sku: "ONE59-BED-004",
    categorySlug: "bedroom",
    catalogType: "evergreen",
    price: 139,
    tone: "sand",
    badge: "Bedroom polish",
    stockStatus: "in_stock",
    summary: "A slim upholstered bench that gives the room a finished look without overwhelming the foot of the bed.",
    highlights: [
      "Useful for outfit changes, folded throws, and next-day bags",
      "Neutral upholstery keeps bedroom palettes calm and flexible",
      "Strong visual payoff for rental bedrooms that need one anchoring piece",
    ],
    dimensions: "W100 × D35 × H46 cm",
    materials: "Solid wood frame, foam cushion, woven polyester upholstery",
    finish: "Soft stone upholstery with walnut-toned legs",
    assembly: "Legs only",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    shape: "bench",
    color: "#8b7867",
    specs: [
      { label: "Best for", value: "Bed-end styling, dressing corners, guest-ready bedrooms" },
      { label: "Care", value: "Vacuum fabric gently and blot spills quickly" },
      { label: "Weight", value: "10.6 kg" },
    ],
    socialProof: {
      rating: 4.7,
      reviews: 22,
      quote: "Our room finally looks intentional instead of just functional.",
      person: "Farah, Seletar",
    },
    alternativeSlugs: ["joo-chiat-bedside-table", "toa-payoh-bedside-caddy"],
  },
  {
    slug: "katong-counter-stool",
    name: "Katong Counter Stool",
    sku: "ONE59-DIN-003",
    categorySlug: "dining",
    catalogType: "drop",
    dropSlug: "payday-reset",
    price: 59,
    tone: "ember",
    badge: "Host-ready",
    stockStatus: "in_stock",
    summary: "A backless counter stool that slides fully away when the kitchen island needs to look clean again.",
    highlights: [
      "Slim seat profile keeps the island area visually lighter",
      "Footrest makes it comfortable enough for quick breakfasts and late-night chats",
      "Easy to pair with warm woods, black frames, and small-space dining setups",
    ],
    dimensions: "W38 × D38 × H66 cm",
    materials: "Powder-coated steel frame, moulded PP seat",
    finish: "Burnt clay seat with black frame",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    shape: "stool",
    color: "#c36b41",
    specs: [
      { label: "Best for", value: "Kitchen islands, breakfast counters, compact entertaining" },
      { label: "Care", value: "Wipe seat with soft damp cloth" },
      { label: "Weight", value: "4.1 kg" },
    ],
    socialProof: {
      rating: 4.8,
      reviews: 33,
      quote: "Looked custom with our kitchen counter and still came in under budget.",
      person: "Jolene, Marine Parade",
    },
    alternativeSlugs: ["bugis-folding-chair", "marina-tray-table"],
  },
  {
    slug: "tiong-bahru-bistro-table",
    name: "Tiong Bahru Bistro Table",
    sku: "ONE59-DIN-004",
    categorySlug: "dining",
    catalogType: "evergreen",
    price: 129,
    tone: "slate",
    badge: "Compact dining fix",
    stockStatus: "low_stock",
    summary: "A round bistro table sized for small kitchens, balcony meals, and two-person dinners that still feel put together.",
    highlights: [
      "Round top makes circulation easier in tight dining zones",
      "Pairs naturally with folding chairs and slim stools",
      "A strong upgrade for renters tired of laptop desks doing dining-table duty",
    ],
    dimensions: "W72 × D72 × H74 cm",
    materials: "Laminate top, powder-coated steel pedestal base",
    finish: "Ash top with graphite base",
    assembly: "Base attachment required",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    shape: "table",
    color: "#607282",
    specs: [
      { label: "Best for", value: "Two-person dining, balconies, compact kitchen corners" },
      { label: "Care", value: "Soft cloth and no harsh scourers" },
      { label: "Weight", value: "12.8 kg" },
    ],
    socialProof: {
      rating: 4.8,
      reviews: 27,
      quote: "Finally found a dining table that fits the flat without making the room feel cramped.",
      person: "Nicholas, Tiong Bahru",
    },
    alternativeSlugs: ["marina-tray-table", "bugis-folding-chair"],
  },
  {
    slug: "kallang-monitor-stand",
    name: "Kallang Monitor Stand",
    sku: "ONE59-WRK-003",
    categorySlug: "workspace",
    catalogType: "evergreen",
    price: 35,
    tone: "slate",
    badge: "Desk lift",
    stockStatus: "in_stock",
    summary: "A raised monitor stand with under-storage space so compact desks feel tidier and less temporary.",
    highlights: [
      "Lifts the screen while freeing space for notebooks and keyboards below",
      "Clean lines help small WFH setups look styled instead of improvised",
      "A quick upgrade that changes the whole desk feel for under S$35",
    ],
    dimensions: "W52 × D20 × H11 cm",
    materials: "Powder-coated steel frame, laminate top panel",
    finish: "Ash top with charcoal frame",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    shape: "shelf",
    color: "#607282",
    specs: [
      { label: "Best for", value: "Monitors, desk organisation, laptop riser duty" },
      { label: "Care", value: "Dry cloth or mild soap on top" },
      { label: "Weight", value: "2.3 kg" },
    ],
    socialProof: {
      rating: 4.9,
      reviews: 67,
      quote: "Cheap in the best way — small spend, huge improvement to my desk.",
      person: "Izzah, Kallang",
    },
    alternativeSlugs: ["paya-laptop-desk", "queenstown-desk-lamp"],
  },
  {
    slug: "upper-thomson-task-chair",
    name: "Upper Thomson Task Chair",
    sku: "ONE59-WRK-004",
    categorySlug: "workspace",
    catalogType: "drop",
    dropSlug: "study-corner",
    price: 139,
    tone: "sand",
    badge: "Study-corner drop",
    stockStatus: "in_stock",
    summary: "A padded task chair that keeps study corners looking warm and home-ready instead of purely office-like.",
    highlights: [
      "Curved back and upholstered seat soften the work-from-home setup visually",
      "Compact wheelbase works better in bedrooms and shared spaces",
      "A comfortable match for longer desk sessions without looking corporate",
    ],
    dimensions: "W58 × D58 × H83-92 cm",
    materials: "Powder-coated steel base, PU casters, foam seat, woven upholstery",
    finish: "Warm stone upholstery with black base",
    assembly: "Seat to base only",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    shape: "chair",
    color: "#907c68",
    specs: [
      { label: "Best for", value: "WFH desks, study corners, bedroom offices" },
      { label: "Care", value: "Vacuum gently and spot clean fabric only" },
      { label: "Weight", value: "9.8 kg" },
    ],
    socialProof: {
      rating: 4.7,
      reviews: 18,
      quote: "Looks like it belongs in the bedroom, not an office storeroom.",
      person: "Hannah, Upper Thomson",
    },
    alternativeSlugs: ["paya-laptop-desk", "kallang-monitor-stand"],
  },
  {
    slug: "seletar-entry-bench-rack",
    name: "Seletar Entry Bench Rack",
    sku: "ONE59-STO-005",
    categorySlug: "storage",
    catalogType: "drop",
    dropSlug: "entryway-flip",
    price: 159,
    tone: "sage",
    badge: "Drop anchor piece",
    stockStatus: "low_stock",
    summary: "A narrow entry bench with a lower rack so shoes, tote bags, and the landing zone all feel more under control.",
    highlights: [
      "Bench seat makes shoe changes easier in tighter foyers",
      "Lower shelf keeps daily pairs visible but more contained",
      "Top-end One59 price point with a much more premium first-impression payoff",
    ],
    dimensions: "W88 × D30 × H48 cm",
    materials: "Powder-coated steel frame, veneer-look top, steel lower shelf",
    finish: "Natural oak top with olive-black frame",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore once the drop opens",
    shape: "bench",
    color: "#6d7d67",
    specs: [
      { label: "Best for", value: "Entryways, drop zones, guest-ready foyers" },
      { label: "Care", value: "Dry cloth and mild cleaner only" },
      { label: "Weight", value: "11.5 kg" },
    ],
    socialProof: {
      rating: 4.8,
      reviews: 16,
      quote: "The sort of entry piece that makes the whole home feel more considered instantly.",
      person: "Sherlyn, Sengkang",
    },
    alternativeSlugs: ["bedok-shoe-rack", "ang-mo-kio-coat-rack"],
  },
];
